### ISSUE TITLE
FieldtypeImageUnrenamed

### ISSUE THREAD

**Issue by matjazpotocnik** [Toutouwai/FieldtypeFileUnrenamed#2]
While this work with files, what would be needed to work with images (and CroppableImage3, FieldtypeSecureFile, ...)? I guess creating a new module? How about adding the option to the details tab on field settings eg. checkbox "Enable unrenamed upload" for all fields that extends FieldtypeFile? I know you don't have that need, just brainstorming :-)

**Comment by Toutouwai** [comment]
I haven't tried it, but I expect FieldtypeImage will be more difficult to do this with because the image variations in PW are handled via the filename.

Also, I can't think of a scenario where, for images rendered as images in the browser (i.e. output as the src attribute of an `<img>` tag), it would make any difference what the filename is. Visitors don't see or use the filename of images that are rendered in the browser. On the other hand, if the images weren't rendered as images in the browser but were provided as downloadable files, then you could just use a File field for them.

**Comment by matjazpotocnik** [comment]
Thank you for your thoughts. Maybe the idea from kongondo to store the original filename into a separate field (https://processwire.com/talk/topic/18148-keep-or-store-originale-file-name/?do=findComment&comment=159025) is another possible approach? And if I understand https://github.com/processwire/processwire/commit/3fb3294f5ae2c3b8fa565202cb5edb3e06bfd5aa, original filename could be stored in a filedata "field"?

**Comment by Toutouwai** [comment]
> And if I understand processwire/processwire@3fb3294, original filename could be stored in a filedata "field"?

Ah, that looks very promising. I suspect Ryan is working on the roadmap item: 
_Add support for custom properties in file/image fields. Currently just description and tags are supported, but it's clear there is strong interest in supporting more here, so we look forward to adding this._

So would probably pay to wait a little while to see how that develops. Storing the filename in custom data would be pretty nice solution - that way it would even be editable in admin if needed. Then when the file needs to be downloaded it can be delivered via wireSendFile() with the original (or edited) filename.

I do worry about security issues with bypassing the core filename sanitization. Because the core sanitizes filenames to a very limited character set on upload and doesn't expect anything different, there could be places where filenames are loaded without the normal protections against script execution or SQL injection - I don't know the codebase well enough to say. PW is pretty secure but vulnerabilities can slip through unnoticed:
https://github.com/processwire/processwire-issues/issues/472
https://github.com/processwire/processwire-issues/issues/471
https://github.com/processwire/processwire-issues/issues/470

If we can keep the standard sanitization and then serve files for download with a custom/original filename then that would be my preference.

**Comment by matjazpotocnik** [comment]
> Storing the filename in custom data would be pretty nice solution - that way it would even be editable in admin if needed. Then when the file needs to be downloaded it can be delivered via wireSendFile() with the original (or edited) filename.

> If we can keep the standard sanitization and then serve files for download with a custom/original filename then that would be my preference.

Yep, this is mine idea. So, let sit and wait.

> I do worry about security issues with bypassing the core filename sanitization. ...

That's another reason that I just showed that it could be done, but refused to make a module. I'm not nearly good enough at understanding PW internals to play with that. Thank you for your time.
